import type { CapabilityInfo, CapabilityKey } from "@trustguard/shared";
import { ADVISORY } from "@trustguard/shared";

/**
 * Evaluates browser capabilities and blind spots honestly.
 * Web browsers strictly isolate web applications from OS processes and hardware internals.
 * We NEVER fabricate device data.
 */
export function getBrowserCapabilities(): CapabilityInfo[] {
  const now = new Date().toISOString();

  return [
    {
      key: "device.installedApps",
      status: "unavailable",
      title: "Installed Applications",
      source: "none",
      reason: "Web browsers run in an isolated sandbox and cannot inspect apps installed on your device.",
      canSee: [],
      cannotSee: [
        "Installed software names",
        "Third-party apps",
        "Application versions",
        "Sideloaded APKs or packages",
      ],
      requiredPermission: "Android QUERY_ALL_PACKAGES / Desktop Native OS API",
      userAction: "Review installed apps manually in your device's System Settings -> Applications.",
      checkedAt: now,
    },
    {
      key: "device.runningApps",
      status: "unavailable",
      title: "Running Applications",
      source: "none",
      reason: "Browsers have no visibility into active processes or other applications currently executing.",
      canSee: [],
      cannotSee: [
        "Currently open applications",
        "Window titles",
        "App CPU or RAM utilization",
      ],
      requiredPermission: "OS Native Process Access",
      userAction: "Use your device's Task Manager or App Switcher to see active running applications.",
      checkedAt: now,
    },
    {
      key: "device.systemProcesses",
      status: "unavailable",
      title: "System & Background Processes",
      source: "none",
      reason: "Web applications cannot access operating system daemon processes or low-level services.",
      canSee: [],
      cannotSee: [
        "Background services",
        "System daemons",
        "Kernel modules",
        "Root/privilege state",
      ],
      requiredPermission: "Root / Admin OS Privilege",
      userAction: "Run an official, certified device antivirus or system security tool.",
      checkedAt: now,
    },
    {
      key: "device.backgroundActivity",
      status: "unavailable",
      title: "Background App Activity",
      source: "none",
      reason: "Browsers cannot monitor what apps do when your screen is locked or in the background.",
      canSee: [],
      cannotSee: [
        "Background network transfers",
        "Periodic background jobs",
        "Wake locks",
      ],
      requiredPermission: "OS Battery & Background Usage Monitor",
      userAction: "Check battery usage in device Settings to identify apps with high background drain.",
      checkedAt: now,
    },
    {
      key: "device.usageStats",
      status: "unavailable",
      title: "App Usage & Screen Time",
      source: "none",
      reason: "Browsers cannot view how often or how long other apps are used.",
      canSee: [],
      cannotSee: [
        "Time spent in other apps",
        "Launch timestamps",
        "Interaction statistics",
      ],
      requiredPermission: "Android Usage Access / iOS Screen Time API",
      userAction: "Review Digital Wellbeing (Android) or Screen Time (iOS) in your device settings.",
      checkedAt: now,
    },
    {
      key: "device.permissions",
      status: "unavailable",
      title: "Device Permissions Auditor",
      source: "none",
      reason: "A website can only request its own browser permissions, not inspect permissions granted to other apps.",
      canSee: ["TrustGuard web app's own browser permissions"],
      cannotSee: [
        "Permissions of other apps (camera, microphone, location, contacts, SMS)",
      ],
      requiredPermission: "OS Permission Manager Access",
      userAction: "Open Device Settings -> Privacy -> Permission Manager to audit app access.",
      checkedAt: now,
    },
    {
      key: "device.storage",
      status: "limited",
      title: "Device & App Storage",
      source: "browser",
      reason: ADVISORY.deviceStorage,
      canSee: [
        "TrustGuard account storage usage (scans, alerts, AI messages, avatars)",
      ],
      cannotSee: [
        "Total hard drive or flash storage capacity",
        "Space consumed by other apps, photos, or media files",
      ],
      requiredPermission: "MANAGE_EXTERNAL_STORAGE / Native Disk API",
      userAction: "Inspect Storage in your device settings for full disk usage breakdown.",
      checkedAt: now,
    },
    {
      key: "device.network",
      status: "limited",
      title: "Network Connection Posture",
      source: "browser",
      reason: "The browser only knows whether it is connected to the internet, not Wi-Fi encryption or router security.",
      canSee: ["Browser online/offline status"],
      cannotSee: [
        "Wi-Fi network encryption type (WPA2/WPA3)",
        "Router firewall configuration",
        "Network-wide packet monitoring",
      ],
      requiredPermission: "OS Network State / Wi-Fi SSID Access",
      userAction: "Avoid conducting sensitive banking on public, unencrypted Wi-Fi networks.",
      checkedAt: now,
    },
    {
      key: "device.securityUpdates",
      status: "unknown",
      title: "OS Security Patch Level",
      source: "none",
      reason: "Browsers do not expose the exact monthly security patch level of your operating system.",
      canSee: ["General operating system family from browser User-Agent"],
      cannotSee: [
        "Exact security patch date",
        "Pending system updates",
        "Kernel build version",
      ],
      requiredPermission: "OS Build Information Access",
      userAction: "Check Settings -> System -> System Update to verify you have the latest updates.",
      checkedAt: now,
    },
    {
      key: "device.os",
      status: "limited",
      title: "Operating System Type",
      source: "browser",
      reason: "Only general platform family is available via browser user agent headers.",
      canSee: ["Operating system family (e.g. Windows, macOS, Android, iOS, Linux)"],
      cannotSee: [
        "Detailed build sub-versions",
        "Installed hotfixes or security patches",
      ],
      requiredPermission: null,
      userAction: "Keep your operating system set to update automatically.",
      checkedAt: now,
    },
    {
      key: "device.model",
      status: "limited",
      title: "Device Model Information",
      source: "browser",
      reason: "Modern browsers deliberately mask hardware identifiers to protect your privacy from fingerprinting.",
      canSee: ["General device category (Desktop / Mobile / Tablet)"],
      cannotSee: ["Serial number", "Exact hardware manufacturer specifications", "IMEI"],
      requiredPermission: null,
      userAction: "No action required.",
      checkedAt: now,
    },
    {
      key: "device.battery",
      status: "limited",
      title: "Battery Health & Status",
      source: "browser",
      reason: "Battery status is restricted or deprecated in modern browsers to prevent fingerprinting.",
      canSee: ["Battery level if Battery API is supported and permitted"],
      cannotSee: ["Hardware battery cycle count", "Battery wear health degradation"],
      requiredPermission: null,
      userAction: "Check Battery settings in device preferences.",
      checkedAt: now,
    },
  ];
}
